#!/usr/bin/env bash
set -e
shopt -s nullglob  # Fixes a case when a directory is empty

# Set up some dirs, using existing vars if specified
export BASEDIR="${BASEDIR:-/ldap}"              # Base directory
export LDAPDIR="${LDAPDIR:-${BASEDIR}/slapd.d}" # LDAP database directory
export SECRETS="${SECRETS:-${BASEDIR}/secrets}" # Secrets to inject into scripts, TLS, etc
export LDIFDIR="${LDIFDIR:-${BASEDIR}/config}"  # Directory for LDAP DB configuration
export CERTDIR="${CERTDIR:-${BASEDIR}/tls}"     # Directory to watch for changes to certificates
export RUN_DIR="${RUN_DIR:-${BASEDIR}/run}"     # Run dir (pid files, sockets, etc)
export LOGNAME=$(basename $0)
export LDAP_DEBUG="${LDAP_DEBUG:-0}"            # Debug must be set to >= 0 prevent forking

write_log() {
   echo "[${LOGNAME}] $@"
}

mkdir -p "${RUN_DIR}"

# Load secrets into environment variables
write_log "Reading secrets..."
for FILE in "${SECRETS}"/*; do
   if [ -f "${FILE}" ]; then
      write_log "Reading $FILE"
      BASE=$(basename $FILE)
      export LDAP_$BASE=$(slappasswd -n -h "{SSHA512}" -o module-load=pw-sha2.la -T $FILE)
   fi
done; write_log "secrets done"

if [ -z "$(ls -A ${LDAPDIR} 2>/dev/null)" ]; then
   mkdir -p "${LDAPDIR}"
      
   # Load initialization items
   write_log "Loading initialization files..."
   for FILE in "${LDIFDIR}"/init*.ldif; do
      write_log "Loading $FILE"
      envsubst < "${FILE}" | slapadd -n0 -F "${LDAPDIR}" -d "${LDAP_DEBUG}"

   done; write_log "initialization complete"

else
   write_log "Skipping initialization; Already configured"
fi

write_log "Starting certificate expiration watcher"
watch_certificates "${CERTDIR}" &

write_log "Starting post-startup configurator"
watch_config "${LDIFDIR}"/config*.ldif &

write_log "Starting LDAP server"
write_log "Listening on ${LDAPURI}"
exec /usr/sbin/slapd -F "${LDAPDIR}" -d "${LDAP_DEBUG}" -h "${LDAPURI}" "$@"
write_log "LDAP terminated with result code $?"
