#!/usr/bin/env bash
#
# watches a directory for changes, then runs the LDIF against the local LDAP
#
set -e

LOGNAME=$(basename $0)
LDAPSASL_MECH=EXTERNAL
ADMINPW=/ldap/secrets/admin

write_log() {
   echo "[${LOGNAME}] $@"
}

config_deleted() {
   write_log "config_deleted $@"
}

config_changed() {
   write_log "config_changed $@"
   envsubst < $2 | ldapadd
}

config_created() {
   write_log "config_created $@"
   envsubst < $2 | ldapadd
}

cert_deleted() {
   write_log "cert_deleted $@"
}

cert_changed() {
   write_log "cert_changed $@"
}

cert_created() {
   write_log "cert_created $@"
}

secret_created() {
   export FILE=$(cat "$1/$2")
}

secret_changed() {
   secret_created "$@"
}

secret_deleted() {
   unset $2
}


# Only watch directories & files
WATCH=()
for F in "$@"; do
   if [ -d "${F}" -o -f "${F}" ]; then
      WATCH+=("${F}")
   else
      write_log "Warning: ${F} is not a directory or a file, removing from watch list"
   fi
done

# Sanity check
if [ ${#WATCH[@]} -eq 0 ]; then
   write_log "Please specify a list of directories to watch"
   exit 1
fi

sleep 10  # Hack to ensure slapd is started before watching for changed files

write_log "Watching for changes in ${WATCH[*]}"
while read DIRECTORY EVENT FILE; do
   case $DIRECTORY in
      "*/secrets/")
         case $EVENT in
            MODIFY*) secret_changed "$DIRECTORY" "$FILE" ;;
            CREATE*) secret_created "$DIRECTORY" "$FILE" ;;
            DELETE*) secret_deleted "$DIRECTORY" "$FILE" ;;
         esac
         ;;
      "*/tls/")
         case $EVENT in
            MODIFY*) cert_changed "$DIRECTORY" "$FILE" ;;
            CREATE*) cert_created "$DIRECTORY" "$FILE" ;;
            DELETE*) cert_deleted "$DIRECTORY" "$FILE" ;;
         esac
         ;;
      "*/config/")
         case $EVENT in
            MODIFY*) config_changed "$DIRECTORY" "$FILE" ;;
            CREATE*) config_created "$DIRECTORY" "$FILE" ;;
            DELETE*) config_deleted "$DIRECTORY" "$FILE" ;;
         esac
         ;;
   esac
done < <(inotifywait -qmre modify,delete,create ${WATCH[*]})
