#!/usr/bin/env sh
#
# watches a directory for changes, then runs the LDIF against the local LDAP
#

config_deleted() {

}

config_changed() {

}

config_created() {

}

cert_deleted() {

}

cert_changed() {

}

cert_created() {

}

secret_created() {
    export FILE=$(cat "$1/$2")
}

secret_changed() {
    secret_created "$@"
}

secret_deleted() {
    unset $2
}

inotifywait -qmre modify,delete,create $1 \
| while read DIRECTORY EVENT FILE; do
    case $DIRECTORY in
        "$1/secrets/")
            case $EVENT in
                MODIFY*) secret_changed "$DIRECTORY" "$FILE" ;;
                CREATE*) secret_created "$DIRECTORY" "$FILE" ;;
                DELETE*) secret_deleted "$DIRECTORY" "$FILE" ;;
            esac
            ;;
        "$1/tls/")
            case $EVENT in
                MODIFY*) cert_changed "$DIRECTORY" "$FILE" ;;
                CREATE*) cert_created "$DIRECTORY" "$FILE" ;;
                DELETE*) cert_deleted "$DIRECTORY" "$FILE" ;;
            esac
            ;;
        "$1/config/")
            case $EVENT in
                MODIFY*) file_changed "$DIRECTORY" "$FILE" ;;
                CREATE*) file_created "$DIRECTORY" "$FILE" ;;
                DELETE*) file_deleted "$DIRECTORY" "$FILE" ;;
            esac
            ;;
done
