#!/usr/bin/env bash
#
# Waits until LDAP is running, then executes the
# file(s) against the running instance. This script
# will run on every start, regardless of whether
# it's already been initialized.
#
set -e
shopt -s nullglob

LOGNAME=$(basename $0)
LDAPSASL_MECH=EXTERNAL

write_log() {
   echo "[${LOGNAME}] $@"
}

load_file() {
   FILE=$1
   if [ -e "${FILE}" ]; then
      write_log "Loading ${FILE}"
      if [ "${LDAP_DEBUG}" -ne "0" ]; then
         envsubst<"${FILE}" | ts "[$LOGNAME]"
      fi
      envsubst<"${FILE}"|ldapmodify -cvQ  2>&1 | ts "[$LOGNAME]"
   else
      write_log "Skipping '$1': file does not exist"
   fi
}

write_log "Waiting for LDAP to start"
while sleep 5s; do
    ldapsearch -s base -QLLLb 'cn=config' 1.1 1>/dev/null 2>&1 && break
done

write_log "LDAP started, processing $@"
for ARG in "$@"; do
   for FILE in "${ARG}"; do
      load_file "${FILE}"
   done
done

write_log "script exited: rc=$!"
