#!/usr/bin/env bash
#
# watches a directory for changes, then runs the LDIF against the local LDAP
#
set -e

LOGNAME=$(basename $0)
LDAPSASL_MECH=EXTERNAL
ADMINPW=/ldap/secrets/admin

write_log() {
   echo "[${LOGNAME}] $@"
}

secret_created() {
   write_log "secret created $@"
   export FILE=$(cat "$1/$2")
}

secret_changed() {
   write_log "secret changed $@"
   secret_created "$@"
}

secret_deleted() {
   write_log "secret deleted $@"
   unset $2
}

# Only watch directories & files
WATCH=()
for F in "$@"; do
   if [ -d "${F}" -o -f "${F}" ]; then
      WATCH+=("${F}")
   else
      write_log "Warning: ${F} is not a directory or a file, removing from watch list"
   fi
done

# Sanity check
if [ ${#WATCH[@]} -eq 0 ]; then
   write_log "Please specify a list of directories to watch"
   exit 1
fi

sleep 10  # Hack to ensure slapd is running before watching for changed files

write_log "Watching for changes in ${WATCH[*]}"
while read DIRECTORY EVENT FILE; do
   case $EVENT in
      MODIFY*) secret_changed "$DIRECTORY" "$FILE" ;;
      CREATE*) secret_created "$DIRECTORY" "$FILE" ;;
      DELETE*) secret_deleted "$DIRECTORY" "$FILE" ;;
   esac
done < <(inotifywait -qmre modify,delete,create ${WATCH[*]})

write_log "script exited: rc=$!"
